Synchronize master branch
sanketq/audience1st pull request #7
Opened 2017-11-07 08:32 UTC by fxdawnn

2017-11-07 08:43 UTC, sanketq approved these changes
lgtm

2017-11-07 08:44 UTC, jayl109 commented
Cherrypick fox’s commit looks good

2017-11-07 19:27 UTC, WayneLeung12 commented
lgtm

2017-11-13 19:10 UTC, WanNJ requested changes
As suggested by Fox, you should fixed those bugs.

2017-11-29 21:14 UTC, closed without merging